server.port=8080

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:eventsdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true

# H2 Console Configuration
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:mysql://localhost:3306/eventsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
# swagger open api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT Security Configuration
security.jwt.secret=MI_SECRETO_DE_32_BYTES_O_MAS____________________
security.jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

